Module3 task1
htmlacademy-nestjs/1486707-readme-2 pull request #5
Opened 2024-04-25 14:46 UTC by vladn255

Сделал подключение к Mongo для file-vault на будущее.
Не работает локально подключение к БД, хотя, вроде, все должно быть правильно

2024-04-25 19:12 UTC, NaumovEvgeniy requested changes

2024-04-25 19:12 UTC, NaumovEvgeniy commented on project/apps/user/docker-compose.dev.yml
> +version: '4.25'
Странная версия, она не поддерживается. [тут](https://docs.docker.com/compose/compose-file/compose-versioning/#version-38) последняя указана как 3.8

2024-04-25 19:12 UTC, NaumovEvgeniy commented on project/apps/user/src/app/author/author.entity.ts
>      this.avatar = data.avatar;
в методе populate мы не все поля присваиваем. например, не присваиваем `passwordHash` из-за которого ломается авторизация пользователя. т.е. сейчас не работает авторизация пользователя

2024-04-25 19:12 UTC, NaumovEvgeniy commented on project/apps/file-vault/src/app/file-uploader/file-uploader.service.ts
> +import { FileVaultRepository } from './file-uploader.repository';
1. Не верный импорт. ts ругается


```
TS2305: Module '"./file-uploader.repository"' has no exported member 'FileVaultRepository'.
    1 | import { Injectable, NotFoundException } from '@nestjs/common';
  > 2 | import { FileVaultRepository } from './file-uploader.repository';

```

2. Так же в этом файле ошибка, в 22 строке. `FileVaultEntity` не принимает параметры, а мы её dto скармливаем

```
ERROR in ./src/app/file-uploader/file-uploader.service.ts:22:41
TS2554: Expected 0 arguments, but got 1.
    20 |
    21 |   public async saveFile(dto: CreateFileItemDto) {
  > 22 |     const newFile = new FileVaultEntity(dto);

```

2024-04-25 19:12 UTC, NaumovEvgeniy commented on project/apps/file-vault/src/app/file-uploader/file-uploader.controller.ts
> +import { AppService } from './file-uploader.service';
Не верный импорт. `AppService` нет такого, есть `FileUploadService`

2024-04-25 19:12 UTC, NaumovEvgeniy commented on project/apps/file-vault/src/app/file-uploader/file-uploader.controller.ts
> +import { AppService } from './file-uploader.service';
Так же на 48 строке, в методе `delete` мы не дожидаемся промиса. т.е. метод закончится выполяться раньше, чем удалится файл

2024-04-26 07:48 UTC, vladn255 commented on project/apps/file-vault/src/app/file-uploader/file-uploader.controller.ts
> +import { AppService } from './file-uploader.service';
Принято, поправил

2024-04-26 07:54 UTC, vladn255 commented on project/apps/file-vault/src/app/file-uploader/file-uploader.service.ts
> +import { FileVaultRepository } from './file-uploader.repository';
Убрал метод saveFile пока - судя по аналогу из учебного проекта, я там поторопился, и реализовывать этот метод надо будет несколько хитрее.

2024-04-26 08:00 UTC, vladn255 commented on project/apps/user/src/app/author/author.entity.ts
>      this.avatar = data.avatar;
Принято, поправил

2024-04-26 18:41 UTC, merged