Module5 task1
htmlacademy-nestjs/1486707-readme-2 pull request #7
Opened 2024-05-31 11:38 UTC by vladn255

Сделал еще не все пользовательские сценарии по Т.З., но подумал, что ПР и так объемный получается, так что лучше убедиться, что я пока на правильном пути))

2024-06-01 06:27 UTC, NaumovEvgeniy requested changes

2024-06-01 06:27 UTC, NaumovEvgeniy commented on project/apps/publication/src/app/article/article.controller.ts
> +    @Body(new CreateArticleValidatorPipe()) dto: CreateArticleDto
не очень красиво выглядят такие пайпы валидации. Во первый, внутри них ты теряешь возможность инжектить зависимости, во вторых под каждую dto тебе нужно делать аж 3 сущности: схему joi, пайп и сам класс dto. 

хочу предложить тоже самое, но на примере кастомного декоратора, который будет валидировать по joi схеме, но более изящно. Тут писать долго, поэтому на консультации бы рассказал)

2024-06-01 06:27 UTC, NaumovEvgeniy commented on project/apps/user/src/app/authentication/authentication.service.ts
> +      sub: user.id,
слишком много информации в токене. 

тк. токен можно расшифровать на фронте без секретного ключа, много лишней информации туда лучше не пихать. достаточно будет только id пользователя, а из этого id ты уже вытащишь все нужные данные.

а вообще в токен нужно передавать только ту информацию, которая зависит от конкретной авторизационной сессии пользователя.

2024-06-01 06:27 UTC, NaumovEvgeniy commented on project/apps/user/src/app/authentication/authentication.service.ts
>      this.authorRepository.update(user.id, user);
не обратил внимание в прошлый раз, тут нужно дожидаться промисов. тут может быть такая ситуация, что пароль не будет выставлен до обновления, потому что мы не должалить промиса на `setPassword`, но уже хотим обновлять

2024-06-05 08:10 UTC, vladn255 commented on project/apps/publication/src/app/article/article.controller.ts
> +    @Body(new CreateArticleValidatorPipe()) dto: CreateArticleDto
Принимается, поправил

2024-06-05 08:10 UTC, vladn255 commented on project/apps/user/src/app/authentication/authentication.service.ts
> +      sub: user.id,
Принимается, поправил

2024-06-05 08:10 UTC, vladn255 commented on project/apps/user/src/app/authentication/authentication.service.ts
>      this.authorRepository.update(user.id, user);
Принимается, поправил

2024-06-05 17:36 UTC, merged