Module6 task1
htmlacademy-nestjs/1486707-readme-2 pull request #8
Opened 2024-06-28 11:12 UTC by vladn255

Сценарий отправки новых публикаций по запросу пока не сделал, так как там надо собирать новые публикации из другого сервиса, и у меня сложилось стойкое ощущение, что делать это надо на уровне API Gateway. Поэтому пока сделал подготовку для этого сценария только.

2024-06-29 08:59 UTC, NaumovEvgeniy requested changes
сейчас не работает отправка почтовых уведомлений при регистрации. Описал возможные пути решения

2024-06-29 08:59 UTC, NaumovEvgeniy commented on project/apps/notifications/notifications.env-example
> +MAIL_SMTP_PORT=25
порт должен быть такой же как в докер композе. `8025`

2024-06-29 08:59 UTC, NaumovEvgeniy commented on project/apps/notifications/notifications.env-example
> +RABBIT_EXCHANGE=readme.notifications
exchange должна быть как и queue. В файле `email-subscriber.controller.ts` он слушает в этой exchange.

2024-06-29 08:59 UTC, NaumovEvgeniy commented on project/apps/user/user.env-example
> +RABBIT_EXCHANGE=readme.notifications
exchange нужна такая же как и queue. Тк контроллер слушает другую

2024-06-29 08:59 UTC, NaumovEvgeniy commented on project/apps/notifications/src/app/email-subscriber/email-subscriber.controller.ts
> +    this.subscriberService.addSubscriber(subscriber);
нужно дождаться промисы через `await`

2024-07-01 07:36 UTC, vladn255 commented on project/apps/notifications/notifications.env-example
> +RABBIT_EXCHANGE=readme.notifications
Поправил в контроллере, подумал, что так будет нагляднее.

2024-07-01 07:36 UTC, vladn255 commented on project/apps/notifications/notifications.env-example
> +MAIL_SMTP_PORT=25
Поправил.

2024-07-01 07:36 UTC, vladn255 commented on project/apps/notifications/src/app/email-subscriber/email-subscriber.controller.ts
> +    this.subscriberService.addSubscriber(subscriber);
Поправил

2024-07-01 07:38 UTC, vladn255 commented on project/apps/user/user.env-example
> +RABBIT_EXCHANGE=readme.notifications
Поправил в контроллере email-subscriber

2024-07-03 04:51 UTC, merged