Module7 task1
htmlacademy-nestjs/1486707-readme-2 pull request #9
Opened 2024-07-17 14:02 UTC by vladn255

Сделал почти все , что было по Т.З., кроме рассылок новых публикаций (в следующей домашке планирую допилить). И пока не сохраняются картинки в постах с ними. Вообще не получилось толком протестить сохранение файлов, потому что не придумал как их правильно мокать в http запросе, чтобы они еще валидацию проходили. И Postman внезапно не может на локалхост отправлять запросы, что было неожиданно, кстати. А в остальном, вроде, все готово))

2024-07-18 19:02 UTC, NaumovEvgeniy requested changes
Понял. Пока не получилось создать пост и без ошибок непонятно что не так..

2024-07-18 19:02 UTC, NaumovEvgeniy commented on project/apps/api-gateway/src/app/articles.http
> +POST http://localhost:4000/api/articles/create HTTP/1.1
Делаю запрос, но ошибка `Bad request` без пояснения, что не так я заполнил. Нужна подробная ошибка

2024-07-18 19:02 UTC, NaumovEvgeniy commented on project/apps/api-gateway/src/app/articles.controller.ts
> +  public async create(@Body() dto: CreateArticleDto & { userId: string }) {
Не получается создать. Говорит `"userId" is not allowed`

2024-07-19 11:32 UTC, vladn255 commented on project/apps/api-gateway/src/app/articles.http
> +POST http://localhost:4000/api/articles/create HTTP/1.1
Добавил дополнительную информацию в аксиовский фильтр, теперь должно проще читаться

2024-07-19 11:32 UTC, vladn255 commented on project/apps/api-gateway/src/app/articles.controller.ts
> +  public async create(@Body() dto: CreateArticleDto & { userId: string }) {
Да, нашел - поправил

2024-07-19 11:34 UTC, vladn255 commented
Добавил еще рассылку новых публикаций, но работает она пока странно. Рассылка благополучно происходит, но где-то в процессе внезапно падает валидация монговская на подписчика. Пока что теряюсь в догадках почему так происходит.

2024-07-19 19:13 UTC, NaumovEvgeniy requested changes
перестал стартовать сервис публикаций...

2024-07-19 19:13 UTC, NaumovEvgeniy commented on project/apps/publication/src/app/app.module.ts
> +import { ConfigUserModule } from '@project/shared/config/user';
Для чего импортируешь модуль конфига для пользователя? У меня сейчас перестал стартовать сервис публикаций.

2024-07-23 19:39 UTC, NaumovEvgeniy requested changes
Понимаю, что надоел, но есть пару моментов и тогда всё будет ок. А так всё кайф

2024-07-23 19:39 UTC, NaumovEvgeniy commented on project/apps/user/src/app/author/rdo/author.rdo.ts
> +  public avatar: unknown;
Сейчас тут отдается буффер. Лучше отдавать более осмысленное или вообще не отдавать

2024-07-23 19:39 UTC, NaumovEvgeniy commented on project/apps/api-gateway/src/app/articles.controller.ts
> +    @UploadedFile(
Сейчас файл всегда является обязательным, хотя у нас есть типы постов, для которых файл не нужен

2024-07-23 19:39 UTC, NaumovEvgeniy commented on project/apps/publication/src/app/article/article.controller.ts
>      return fillDto(ArticleRdo, updatedArticle.toPOJO());
Сейчас не проверяется пользователь при обновлении. Т.е. пост может создать один пользователь, а обновить другой (не владелец)

2024-07-23 19:39 UTC, NaumovEvgeniy commented on project/apps/publication/src/app/article/article.controller.ts
>      return fillDto(ArticleRdo, updatedArticle.toPOJO());
При удалении тоже не проверяется пользователь

2024-07-24 09:40 UTC, vladn255 commented on project/apps/user/src/app/author/rdo/author.rdo.ts
> +  public avatar: unknown;
Согласен - убрал от греха подальше)

2024-07-24 09:40 UTC, vladn255 commented on project/apps/api-gateway/src/app/articles.controller.ts
> +    @UploadedFile(
Поправил.

2024-07-24 09:41 UTC, vladn255 commented on project/apps/publication/src/app/article/article.controller.ts
>      return fillDto(ArticleRdo, updatedArticle.toPOJO());
Поправил на уровне api-gateway.

2024-07-24 09:41 UTC, vladn255 commented
Добавил еще описание в Readme, чтобы проверяющему проще было соориентироваться сразу

2024-07-24 18:42 UTC, merged